name: Wind Data Collector

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC (8 AM Berlin time)
  workflow_dispatch:    # Allows manual triggering

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin python-dotenv
      
      - name: Create Firebase service account file
        run: |
          mkdir -p .secrets
          cat << 'EOF' > .secrets/serviceAccountKey.json
          ${{ secrets.FIREBASE_CREDENTIALS }}
          EOF
      
      - name: Run collector
        run: python scrape.py