name: Wind Data Collector

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin
      
      - name: Create Firebase service account file
        run: |
          mkdir -p .secrets
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > .secrets/serviceAccountKey.json
      
      - name: Run collector
        run: python wind_data_collector.py