name: Wind Data Collector

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6:00 AM UTC every day
  workflow_dispatch:     # Allows manual triggering

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin python-dotenv jq
      
      - name: Create Firebase service account file
        run: |
          mkdir -p .secrets
          echo '${{ secrets.FIREBASE_CREDENTIALS }}' > .secrets/serviceAccountKey.json
          # Verify the file was created correctly
          ls -la .secrets/
          head -n 5 .secrets/serviceAccountKey.json
          # Validate JSON syntax
          jq empty .secrets/serviceAccountKey.json || (echo "Invalid JSON!" && exit 1)
      
      - name: Run collector
        run: python scraper.py
      
      - name: Clean up sensitive files
        run: |
          rm -rf .secrets
          echo "Cleaned up sensitive files"