name: Wind Data Collector

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin python-dotenv
      
      - name: Create Firebase service account file
        run: |
          mkdir -p .secrets
          cat << 'EOF' > .secrets/serviceAccountKey.json
          ${{ secrets.FIREBASE_CREDENTIALS }}
          EOF
      
      - name: List files (for debugging)
        run: ls -la
      
      - name: Run collector
        run: |
          if [ -f "scraper.py" ]; then
            python scraper.py
          else
            echo "Error: scraper.py not found in root directory!"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi