name: Daily Wind Data Scraper

on:
  schedule:
    # Runs daily at 5:00 AM UTC (6:00 AM CET/7:00 AM CEST)
    - cron: '0 5 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  scrape-wind-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install selenium firebase-admin
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: Setup Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          fonts-liberation \
          libasound2 \
          libatk-bridge2.0-0 \
          libatspi2.0-0 \
          libdrm2 \
          libgtk-3-0 \
          libgtk-4-1 \
          libnspr4 \
          libnss3 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          xvfb
    
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Run wind data scraper
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        DISPLAY: :99
      run: |
        # Start virtual display
        Xvfb :99 -ac -screen 0 1920x1080x24 &
        sleep 3
        python github_action_windfinder.py
      timeout-minutes: 20
    
    - name: Log completion
      run: |
        echo "Wind data scraping completed at $(date)"